### ISSUE TITLE
at the first installation it appears in an unusual way

### ISSUE THREAD

**Issue by maofree** [TecArt/grav-plugin-tecart-cookie-manager#10]
Hi
I've installed the plugin, without any changes, in the fron-end the graphics and text appear differently than they should be, the settings in the plugin configuration are not taken into account in the front block

![2](https://user-images.githubusercontent.com/653230/187026295-4ba11cb1-ce72-47b6-87b5-9e368e60e52c.png)

![3](https://user-images.githubusercontent.com/653230/187026315-09916e4c-90b7-4836-96f8-f8156ac765a4.png)

thanks

**Comment by ChristianaHoJo** [comment]
Have you add categories and scripts. Maybe you have to empty Cache? Cannot reproduce this issue. It also works for other users.

**Comment by maofree** [comment]
Hi
I have not created categories or scripts, at the moment there are no tracking scripts
I'll check later

**Comment by ChristianaHoJo** [comment]
In this case the problem probably is that the settings are not in the correct directory or are not retrieved from the correct directory. The settings can be made in the plugin settings under admin->plugins->tecart-cookie-manager. The problem could also be a permission problem or the selected directory does not exist.
![issue#10_2022-10-25_08-22](https://user-images.githubusercontent.com/71634299/197701042-69f9de1c-2df7-46f7-a997-38f773cc1cb1.png)
