### ISSUE TITLE
Possibility to add scr-attribute into the script-tag

### ISSUE THREAD

**Issue by gitbitpi** [TecArt/grav-plugin-tecart-cookie-manager#12]
Hi,
correct me if i'm wrong. Because the script-Tag is added from the plugin, it is not possible to add a scr-attribute into the script-tag. It would be perfect if this is possible.
Thanks in advance!

**Comment by ChristianaHoJo** [comment]
Hi!
yes the plugin writes the script-Tag. You can choose between script and noscript Tag. Currently we lack the capacity to further develop the open source project. You may be able to temporarily load the script using a load function within the script tags or copy the code from the script file directly into the text field .

**Comment by gitbitpi** [comment]
Thanks for your answer and the plugin. Good to know...

**Comment by ChristianaHoJo** [comment]
you are very welcome to make the option available as a pull request :-)
