### ISSUE TITLE
Add SameSite Attribut

### ISSUE THREAD

**Issue by JS-Media-Creation** [TecArt/grav-plugin-tecart-cookie-manager#19]
In the firefox warnings it says that the "SameSite-Attribute" doesn't have a valid value. It's missing in the "cookieconsent_categories", "cookieconsent_onscroll_scripts" and the "cookieconsent_scripts". Can you maybe add, that the plugin adds `SameSite=Lax` to them? This would cause the same behaviour as if the attribut is not set.

**Comment by ChristianaHoJo** [comment]
Hi @JS-Media-Creation,
thank you for reporting this issue. We have updated the plugin to add the "SameSite" attribute to "Lax" for the affected cookies ("cookieconsent_categories", "cookieconsent_onscroll_scripts" and "cookieconsent_scripts"). This should make the behavior consistent and in line with Firefox warnings. Please check the latest version of the plugin (v0.1.14)
