### ISSUE TITLE
Not working properly - runs the scripts before you consent or if you reject

### ISSUE THREAD

**Issue by kibkib** [TecArt/grav-plugin-tecart-cookie-manager#24]
It does not work properly, it runs the script after entering the page, it does not wait for the consent. And it runs it even if you select "only esentials" button.
You can test it by entering alert('TEST'); into the script section and you receive the alert before you consent. It runs the script also if you select only esentials button. It only does not run (after reloading) if you select settings and disable it manually. 

It doesn't work on the developer page www.tecart.de either. If you check the cookies with and without consent , there is no difference.
![cookies](https://github.com/user-attachments/assets/34a7aede-1d70-4813-95e0-04967fff115d)

**Comment by kibkib** [comment]
oh, I understand now the logic. 
https://github.com/TecArt/grav-plugin-tecart-cookie-manager/issues/20

I thought the category opt-in button is to allow the user to opt-out all scripts in the category. But it means all scipts in the category are run before consent.

**Comment by pamtbaau** [comment]
Please feedback your enlightenment on Discourse for the benefit of the community. Thanks!

**Comment by ChristianaHoJo** [comment]
Hi @kibkib,

that's right, if all cookies are activated in "Category", this applies globally to all scripts within this category, regardless of what is set for the individual scripts.  This was desired by the requirements of the plugin. Is it now working for you now?

Best regards,
Christiana

**Comment by kibkib** [comment]
Thanks. It worked at athe end, but other tags in google tag manager did not access the consent status.
I switched to https://github.com/68publishers/cookie-consent which is very easy to install thru GTM, the consent status works for other tags and the consent is multilanguage.
