### ISSUE TITLE
Incluce Analytics Tag with Tagmanager

### ISSUE THREAD

**Issue by nikaindl** [TecArt/grav-plugin-tecart-cookie-manager#3]
How would you include the general Analytics Tag with the Tagmanager snippet? Since your plugin already ads the script tags, this code would not work:

<script async src="https://www.googletagmanager.com/gtag/js?id=X-XXXXXXXXX"></script>

**Comment by pamtbaau** [comment]
If I'm not mistaken, the GTM inline script you've added to the "Scripts" tab in Admin and which in turn is added to the DOM by the plugin, will load all required scripts to run Google Analytics.

**Comment by ChristianaHoJo** [comment]
@nikaindl just copy the code that should be wrapped inside "script" a tag.  In script tab in admin you could choose between "<script>" and "<noscript>" tag. The content from the code text field is automatically wrapped in the tag and the plugin adds this tag to DOM. So you need to copy the inline scripts of GTM to the cookie manager 
![image](https://user-images.githubusercontent.com/71634299/155949210-6cc1f586-aa0b-4aa1-b3b6-bc864e871448.png)
