### ISSUE TITLE
preload of css files not working

### ISSUE THREAD

**Issue by jochenmichels** [TecArt/grav-plugin-tecart-cookie-manager#4]
Hi, I realised after upgrading to v0.14 that the two css files
- cookieconsent.min.css
- tecart-cookie-manager.min.css
 
are not loaded at all. In the console of chrome or firefox the newly added rel="reload" attributes seem to cause these problems (Firefox was missing the 'as' atttribute and Chrome declares a timing problem).
I was only able to fix this by removing the rel atrributes in tecart-cookie-manager.php:
v0.14:
```
160            // Add plugin CSS files to the grav assets.
161           $assets->addCss($this->assetsPath . $this->cookieConsentCSS, array('rel' => 'preload'));
162           $assets->addCss($this->assetsPath . $this->customCSS, array('rel' => 'preload'));
```
patched:
```
160            // Add plugin CSS files to the grav assets.
161           $assets->addCss($this->assetsPath . $this->cookieConsentCSS);
162           $assets->addCss($this->assetsPath . $this->customCSS);
```
best wishes
Jochen

**Comment by ChristianaHoJo** [comment]
Hi Jochen,

I have changed it to "re=stylesheets" in new release. Was an issue of a local project and but is an error for global plugin.
`      // Add plugin CSS files to the grav assets.
            $assets->addCss($this->assetsPath . $this->cookieConsentCSS, array('rel' => 'stylesheet'));
            $assets->addCss($this->assetsPath . $this->customCSS, array('rel' => 'stylesheet'));`
