### ISSUE TITLE
Please follow up on outstanding issues and pull requests

### ISSUE THREAD

**Issue by pamtbaau** [TecArt/grav-plugin-tecart-cookie-manager#5]
@ChristianaHoJo, Would you mind following up on outstanding issues and pull requests? People have taken the effort to report an issue and have also created a pull request as early as Oct 2021 and you haven't responded yet.

Thanks!

**Comment by pamtbaau** [comment]
Thanks @ChristianaHoJo. Unfortunately, one of your commits has undone the PR of @mcdeck which fixed a missing `|raw` filter.

**Comment by ChristianaHoJo** [comment]
Sorry. I have pushed and merged it again!
