### ISSUE TITLE
By default cookies are not blocked, deny button doesn't remove cookies

### ISSUE THREAD

**Issue by 01Kuzma** [TecArt/grav-plugin-tecart-cookie-manager#8]
Hi,
it seems that there is a bug.
I've made two categories: "system cookies" and "analytics + ads".

The first category has `opt-in for all cookies ` set to `hide`.
The second category has `opt-in for all cookies ` set to `show`.

I've inserted the code from the Google Tag Manager in `<scripts>` area. My GTM container inserts: GA, Google AdWords and Facebook Pixel.
`Script Settings`: Default (script included or not) set to `not active`. Here I provided the screenshot:
![image](https://user-images.githubusercontent.com/569504/182639846-16338fc5-d240-4ef3-886a-2423497014b8.png)

The problem: once I visit the page all cookies are allowed and not blocked! If I navigate to banner settings the script category is active! While it should be turned off.
Then I click `deny` button, but the status of the script is still allowed:
![image](https://user-images.githubusercontent.com/569504/182640478-6e1e8211-5a35-46c3-bace-a0a2deafde45.png)
Then manually I untick `opt-in` checkbox and press save settings button, and as the result, the vast majority of marketing cookies are deleted, system cookies still exist, but the one cookie from GA still not removed `_ga_XXX`
![image](https://user-images.githubusercontent.com/569504/182641108-fc614ce1-6371-4d39-9945-b0a858f8b55e.png)

**Comment by ChristianaHoJo** [comment]
Hi Kuzma,

to which category do the scripts belong? 
If category with option visible is choosen, then the toggler category is output, set to "on" and **all scripts/cookies of this category are initially activated**. 

![grafik](https://user-images.githubusercontent.com/71634299/182774415-a9604515-388c-4d10-b083-c141f0732d02.png)

The setting is the same effect as if you would set the toggle in frontend for all cookies of this category to active:
![grafik](https://user-images.githubusercontent.com/71634299/182775039-e35f3519-47f0-400a-9edb-9099d2735d27.png)

**Comment by 01Kuzma** [comment]
@ChristianaHoJo , thank you for your reply!
Well, I will demonstrate with screenshots, it will be easier.
I want to achieve a simple cookie blocker with two categories.
1). Required cookies - session etc. As they are internal cookies we are unable to block them, so it's a blank screen just for visitor information purposes.
2). GTM script, which should be blocked by default, turned on if a visitor press `Allow` or choose it from banner settings and clicks `save settings`.

Here are my settings:
1). categories
![image](https://user-images.githubusercontent.com/569504/182785114-dc657fe2-d509-491c-bb43-2dd0e1e66969.png)
2). scripts
![image](https://user-images.githubusercontent.com/569504/182794160-de72a4f4-dd09-4c2c-b8c6-6f2e7bd10f4c.png)

So, once I visit the page from a private mode all cookies are not blocked (the internal cookie names here is in Lithuanian, not in English, sorry for that)
![image](https://user-images.githubusercontent.com/569504/182794727-61c14cee-b474-4623-8cc8-9a1ab4f595bf.png)

The settings in banner are `on` by default:
![image](https://user-images.githubusercontent.com/569504/182795107-ba410c80-ff78-4056-b2c0-f10af3dc8879.png)

If I switch two checkboxes press save, only the last checkbox is off, but cookies are also loaded.
![image](https://user-images.githubusercontent.com/569504/182795343-8fcfa98e-092d-4eb9-86ea-3f5c572453f7.png)

And the last option - I press `Decline` button, cookies are not deleted.

Something is bad in my config?

**Comment by 01Kuzma** [comment]
How can I turn it off by default within provided settings?

**Comment by ChristianaHoJo** [comment]
You can turn it off when turn off "show" in category settings.

**Comment by 01Kuzma** [comment]
@ChristianaHoJo, thank you!
It seems that it's what I'm looking for! I will test it a little bit further.
Maybe it's off-topic and relates to how the GA works, but I think it should be mentioned in the GDPR era :)
After a user Clicks `Accept` all GA, ADS and other cookies are loaded, then the user clicks the `Decline`. After it all mentioned cookies are deleted, but a particular cookie with it's unique `ID` still exists - `_ga_XXX`.
Have you observed such behaviour?

**Comment by ChristianaHoJo** [comment]
I hope you'll get it work now. :-)
We use the plugin ourselves (www.tecart.de) and our editors say it works as expected. However, our marketing department has separated from the Google Tag Manager, which is why I have no current information.
