### ISSUE TITLE
the plugin is not multilingual

### ISSUE THREAD

**Issue by maofree** [TecArt/grav-plugin-tecart-cookie-manager#9]
Hi
I'm testing the plugin, but I think it is not possible to use it on a multi-lang website, languages.yaml and the files inside languages folder are used just for the admin texts.
with the other plugin "simple-cookie" it is possible to do it by languages.yaml
is there a solution?

I think the best solution is using the languages.yaml file, because it is possible to add the traslations directly in the languages.yaml of the theme without change any files of the plugin

thanks

**Comment by ChristianaHoJo** [comment]
The plugin is not yet developed for multilingualism. Unfortunately, we don't have enough free resources at the moment to continue working on it. But we'll put it on the ToDo list!

**Comment by ChristianaHoJo** [comment]
you are very welcome to make the option available as a pull request :-)

**Comment by ChristianaHoJo** [comment]
A French translation is now available
https://github.com/TecArt/grav-plugin-tecart-cookie-manager/pull/13
